server:
  port: 8080
  servlet:
    context-path: /pickandgo

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/pickandgodb?createDatabaseIfNotExist=true
    password:
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  sql:
    init:
      mode: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: pickandgo.sdp@gmail.com
    password: pickandgo
    protocol: smtp
#    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

  main:
    allow-circular-references: true